#!/bin/bash -e

CLOUD_PROVIDER="${CLOUD_PROVIDER:-aws}"

if ! tofu -chdir="opentofu/${CLOUD_PROVIDER}/" fmt -check; then
    tofu -chdir="opentofu/${CLOUD_PROVIDER}/" fmt
    echo "Formatting issues detected and fixed, please stage the new changes" 1>&2
    echo "Your changes were NOT committed" 1>&2
    exit 1
fi
